Update integrate.yml

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -2,7 +2,9 @@ name: Branch Integration
 
 on:
   pull_request:
-    branches: [production]
+    branches:
+      - dev
+      - main
 
 jobs:
   # Build job
@@ -19,12 +21,11 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
           cache: "npm"
-      - name: Set environment variables
-        run: echo "Setting environment variables"
-        env:
-          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
-          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
-          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
-          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
       - run: npm ci
       - run: npm run build --if-present
+      - name: Check for build errors
+        run: |
+          if [ $(find . -name "*.js" -type f -exec grep -l "Failed to compile" {} \; | wc -l) -gt 0 ]; then
+            echo "Build errors found"
+            exit 1
+          fi
