Update integrate.yml

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -2,7 +2,9 @@ name: Branch Integration
 
 on:
   pull_request:
-    branches: [dev]
+    branches:
+      - dev
+      - main
 
 jobs:
   # Build job
@@ -21,3 +23,11 @@ jobs:
           cache: "npm"
       - run: npm ci
       - run: npm run build --if-present
+      - name: Test
+        run: npm run test
+      - name: Check for build errors
+        run: |
+          if [ $(find . -name "*.js" -type f -exec grep -l "Failed to compile" {} \; | wc -l) -gt 0 ]; then
+            echo "Build errors found"
+            exit 1
+          fi
